name: MinecraftParty_by_Groodian
main: de.groodian.minecraftparty.main.Main
author: Groodian
version: 4.0

commands:
   mpsetup:
      description: Setting up the game
   start:
      description: Starting the game
   build:
      description: Build mode
   stats:
      description: Stats
   minecraftparty:
      description: Information about the plugin
      aliases: [mp]